"""empty message

Revision ID: c0a94ec0882d
Revises: a1d2788d7d53
Create Date: 2021-12-05 21:44:31.853195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0a94ec0882d'
down_revision = 'a1d2788d7d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'user_name')
    op.drop_column('favorite', 'character_name')
    op.drop_column('favorite', 'planet_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('planet_name', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('favorite', sa.Column('character_name', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('favorite', sa.Column('user_name', mysql.VARCHAR(length=250), nullable=False))
    # ### end Alembic commands ###
