"""empty message

Revision ID: e283280e12be
Revises: 5ac6c2867896
Create Date: 2021-12-04 15:32:47.330075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e283280e12be'
down_revision = '5ac6c2867896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite__character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=250), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('character_name', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite__planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=250), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('planet_name', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('character_name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('planet_name', mysql.VARCHAR(length=250), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favorite_ibfk_1'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favorite_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('favorite__planet')
    op.drop_table('favorite__character')
    # ### end Alembic commands ###
